wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.7
    cli_version: 0.23.1
    framework: huggingface
    huggingface_version: 4.57.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1765573638
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      2:
      - 1
      - 11
      - 41
      - 49
      3:
      - 4
      - 13
      - 16
      - 37
      - 42
      4: 3.13.7
      5: 0.23.1
      6: 4.57.3
      13: linux-x86_64
    e:
      kfmg4bt6jwh86icamq94r7wkhckvlfrf:
        os: Linux-5.14.0-427.50.1.el9_4.x86_64-x86_64-with-glibc2.34
        python: CPython 3.13.7
        started_at: '2025-12-12T21:07:04.965Z'
        args:
        - --local_rank=0
        - --port
        - '59875'
        program: /home/jcdutoit/Projects/probability-aligned-llms/main.py
        code_path: main.py
        code_path_local: main.py
        git:
          remote_url: git@github.com:josephdutoit/probability-aligned-llms.git
          commit: 78fb928b921f94bfbe471b7b410ebccc69743b8b
        root: /home/jcdutoit/Projects/probability-aligned-llms
        host: m13l-2-1
        executable: /home/jcdutoit/Projects/probability-aligned-llms/.venv/bin/python3
        cpu_count: 64
        cpu_count_logical: 64
        gpu_type: NVIDIA L40S
        gpu_count: 3
        disk:
          /:
            total: '549755813888000'
            used: '2928629383168'
        memory:
          total: '540390031360'
        gpu_nvidia:
        - name: NVIDIA L40S
          memory_total: '48305799168'
          cuda_cores: 18176
          architecture: Ada
          uuid: GPU-4f79e793-1620-cbc4-cb52-5fd5c79ab66c
        - name: NVIDIA L40S
          memory_total: '48305799168'
          cuda_cores: 18176
          architecture: Ada
          uuid: GPU-0ff31c8f-2437-1b57-9653-2c11f3871dcd
        - name: NVIDIA L40S
          memory_total: '48305799168'
          cuda_cores: 18176
          architecture: Ada
          uuid: GPU-9f670ded-76cf-7904-d97a-341c9503daa7
        cuda_version: '12.8'
        slurm:
          job_id: '9004310'
        writer_id: kfmg4bt6jwh86icamq94r7wkhckvlfrf
model_path:
  desc: null
  value: Qwen/Qwen2.5-3B
beta:
  desc: null
  value: 0.04
all_steps:
  desc: null
  value: 500
Q_batch_size:
  desc: null
  value: 1
num_pre_Q:
  desc: null
  value: 3
train_batch_size:
  desc: null
  value: 1
gen_update_steps:
  desc: null
  value: 6
clip_param:
  desc: null
  value: 0.2
compute_gen_logps:
  desc: null
  value: true
